### ISSUE TITLE
Feature: User can add the id of the technician and add more than 1 technician per OT

### ISSUE THREAD

**Issue by ssantosb** [DanielZambSB/Equipo-IA#23]
**Is your feature request related to a problem? Please describe.**
The user can only add right now 1 technician per OT and it doesn't provide the id field.

**Describe the solution you'd like**
The user should be able to add more than 1 technician per OT and provide the id for every one of them. 

This change needs to be implemented in the screens: 

- Provider assignment from call center. 
- Automatic "uber" provider assignment.

**Comment by DanielZambSB** [comment]
Not going to implment this feature
